services:
  db:
    image: mysql:8.0 # use the latest mysql image
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # set the root password
    ports:
      - 3306:3306 # map the port to the host
    volumes:
    - db_data:/var/lib/mysql # mount the volume to persist the data

volumes:
  db_data: # named volume